In [ ]:
!pip install openai pandas tqdm # для запросов к моделям через OpenRouter

import os
import time
import json
import random
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

from tqdm import tqdm
from openai import OpenAI
from getpass import getpass # для безопасного ввода API-ключа.

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.32.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.14.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.13)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
# ввожу ключ от OpenRouter
os.environ["OPENROUTER_API_KEY"] = getpass("OpenRouter API key: ")

OpenRouter API key: ··········

In [ ]:
client = OpenAI(
    api_key=os.environ["OPENROUTER_API_KEY"],
    base_url="https://openrouter.ai/api/v1"
)

In [ ]:
#Загрузка подготовленного датасета (школьники + сгенерированные тексты)
df = pd.read_csv("final_dataset.csv")
df = df.dropna(subset=["text", "label"])
df["text"] = df["text"].astype(str)
df["label"] = df["label"].str.lower()
print(df["label"].value_counts())
df.head()

label
human    1236
ai       1212
Name: count, dtype: int64

,source_id,text,label,model,prompt_type
0,0,В своем произведении Горький ставит вопрос: «Ч...,human,human,none
1,1,"Каждый член семьи незаменим, ведь родные для н...",human,human,none
2,2,"Каждый человек должен не забывать читать, ведь...",human,human,none
3,3,"Пожалуй, ни для кого не будет секретом, что А....",human,human,none
4,4,Доброта — это хорошее отношение к другим. В да...,human,human,none

In [ ]:
# определяю модели для бейзлайна

BASELINE_MODELS = [
  #  "x-ai/grok-4.1-fast",
   # "openai/gpt-5.4-mini"
    "deepseek/deepseek-v4-flash"
]

In [ ]:
# Задаю промт для детекции


DETECTION_PROMPT = """
Ты эксперт по анализу школьных сочинений на русском языке.

Тебе дан текст сочинения.
Нужно определить:
- написан ли текст человеком;
- или сгенерирован языковой моделью.

Важно:
Современные LLM способны:
- имитировать школьный стиль;
- использовать разговорные конструкции;
- допускать мелкие ошибки;
- делать текст менее академичным;
- намеренно humanize output.

Поэтому:
- ошибки не означают human;
- разговорный стиль не обязательно  human;
- эмоциональность не обязательно означает human.

Однако:
- многие реальные школьные сочинения также:
  - неровные;
  - противоречивые;
  - шаблонные;
  - эмоциональные;
  - плохо структурированные.

Поэтому нельзя автоматически считать текст AI-generated только из-за:
- хорошей связности;
- литературности;
- шаблонных рассуждений;
- плавных переходов.

Анализируй более глубокие признаки:
- статистическую сглаженность текста;
- повторяемость структуры аргументации;
- чрезмерно универсальные выводы;
- одинаковый ритм абзацев;
- отсутствие естественных семантических неровностей;
- неестественно стабильный тон сочинения;
- искусственную равномерность качества текста.

Особенно важно:
Реальные школьные тексты часто содержат:
- случайные скачки мысли;
- неровную логику;
- локальные противоречия;
- неидеальные переходы;
- избыточные или странные фразы;
- эмоциональные перегибы.

Не классифицируй текст как AI без достаточного количества признаков генерации.

Если признаки генерации неоднозначны,
оцени совокупность stylistic и semantic паттернов.
Не используй все время слишком консервативную или слишком агрессивную стратегию.

Сначала  проанализируй весь текст по этим правилам,
В ответе верни только JSON.

Формат ответа:

{{
  "label": "human" или "ai",
  "confidence": число от 0 до 1
}}

Никаких пояснений.
Никакого markdown.
Только JSON.

Текст:
{text}
"""

In [ ]:
# Функция для детекции
# на выходе по каждому тиексту получаю pred_label - human или ai и  confidence - уверенность модели

def detect_text(model, text, max_retries=3):

    prompt = DETECTION_PROMPT.format(
        text=text
    )

    for attempt in range(max_retries):

        try:
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {
                        "role": "system",
                        "content": "Ты AI detector. "
                            "Отвечай только валидным JSON. "
                            "Без пояснений."
                    },
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                temperature=0,
                max_tokens=100
            )

            raw_answer = response.choices[0].message.content.strip()
            data = json.loads(raw_answer)
            pred_label = data["label"].lower()
            confidence = float(data["confidence"])
            return pred_label, confidence, raw_answer

        except Exception as e:
            print("Ошибка:", e)
            print("Попытка:", attempt + 1)

            time.sleep(3)

    return None, None, None

In [ ]:
# прогоняем все тексты через все baseline-модели

results_path = "baseline_results.csv"

results = []

for model in BASELINE_MODELS:

    print(f"\n baseline model: {model}")

    for i, row in tqdm(df.iterrows(), total=len(df)):

        text = row["text"]
        true_label = row["label"]

        pred_label, confidence, raw_answer = detect_text(
            model=model,
            text=text
        )

        result = {
            "id": i,
            "text": text,
            "true_label": true_label,
            "pred_label": pred_label,
            "confidence": confidence,
            "baseline_model": model,
            "raw_answer": raw_answer
        }

        results.append(result)

        #  результат
        pd.DataFrame(results).to_csv(
            results_path,
            index=False,
            encoding="utf-8-sig"
        )

        time.sleep(1)

baseline_df = pd.DataFrame(results)

baseline_df.head()

 baseline model: deepseek/deepseek-v4-flash

  0%|          | 0/2448 [00:00<?, ?it/s]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  0%|          | 2/2448 [00:11<3:34:59,  5.27s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  0%|          | 7/2448 [00:54<3:59:22,  5.88s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

  1%|          | 24/2448 [02:42<2:40:30,  3.97s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  2%|▏         | 41/2448 [04:24<2:24:37,  3.61s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  2%|▏         | 45/2448 [04:42<2:29:42,  3.74s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  2%|▏         | 53/2448 [05:33<3:12:59,  4.83s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  3%|▎         | 72/2448 [06:28<2:15:27,  3.42s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  3%|▎         | 82/2448 [08:04<5:42:00,  8.67s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

  3%|▎         | 84/2448 [09:04<11:18:57, 17.23s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

  3%|▎         | 85/2448 [09:34<13:51:03, 21.10s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

  4%|▎         | 87/2448 [10:01<10:43:22, 16.35s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  4%|▎         | 91/2448 [10:41<6:36:48, 10.10s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  4%|▍         | 95/2448 [11:12<4:17:17,  6.56s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  4%|▍         | 100/2448 [11:38<3:03:11,  4.68s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

  4%|▍         | 101/2448 [12:22<10:35:08, 16.24s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

  4%|▍         | 103/2448 [13:12<12:56:24, 19.87s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

  4%|▍         | 104/2448 [13:35<13:24:52, 20.60s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

  5%|▍         | 112/2448 [14:22<3:34:03,  5.50s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

  5%|▍         | 113/2448 [14:44<6:41:44, 10.32s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  5%|▍         | 116/2448 [15:18<6:34:46, 10.16s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  5%|▍         | 118/2448 [15:35<5:45:45,  8.90s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  6%|▌         | 150/2448 [18:29<2:41:30,  4.22s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  6%|▌         | 151/2448 [18:41<4:05:14,  6.41s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  6%|▋         | 156/2448 [19:12<4:26:29,  6.98s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  7%|▋         | 168/2448 [20:20<3:22:38,  5.33s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  7%|▋         | 174/2448 [20:52<2:34:47,  4.08s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  7%|▋         | 176/2448 [21:06<3:15:30,  5.16s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  7%|▋         | 180/2448 [21:24<2:41:47,  4.28s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  8%|▊         | 197/2448 [23:10<3:51:13,  6.16s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

  8%|▊         | 206/2448 [24:25<3:59:14,  6.40s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  9%|▉         | 227/2448 [25:57<1:56:50,  3.16s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  9%|▉         | 230/2448 [26:20<3:10:47,  5.16s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

  9%|▉         | 232/2448 [26:42<4:50:47,  7.87s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 10%|▉         | 234/2448 [27:13<6:36:07, 10.74s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 10%|█         | 246/2448 [28:34<2:30:27,  4.10s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 10%|█         | 255/2448 [29:39<3:04:59,  5.06s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 11%|█         | 261/2448 [30:15<2:29:20,  4.10s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 11%|█         | 263/2448 [30:30<3:15:01,  5.36s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 11%|█         | 265/2448 [30:43<3:22:30,  5.57s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 11%|█         | 266/2448 [31:18<8:41:22, 14.34s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 11%|█         | 271/2448 [31:45<3:33:46,  5.89s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 12%|█▏        | 283/2448 [32:50<2:27:15,  4.08s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 12%|█▏        | 286/2448 [33:32<5:02:40,  8.40s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 12%|█▏        | 288/2448 [33:46<4:24:09,  7.34s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 12%|█▏        | 296/2448 [35:06<4:02:38,  6.77s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 12%|█▏        | 300/2448 [35:24<2:40:08,  4.47s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 12%|█▏        | 301/2448 [35:49<6:16:49, 10.53s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 12%|█▏        | 303/2448 [36:16<7:23:49, 12.41s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 12%|█▎        | 306/2448 [36:33<4:24:36,  7.41s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 13%|█▎        | 308/2448 [37:01<5:45:27,  9.69s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 13%|█▎        | 314/2448 [37:37<3:03:52,  5.17s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 13%|█▎        | 326/2448 [38:27<2:16:40,  3.86s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 13%|█▎        | 328/2448 [38:41<3:01:43,  5.14s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 14%|█▎        | 335/2448 [39:42<2:57:40,  5.05s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 14%|█▍        | 337/2448 [40:04<4:16:07,  7.28s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 14%|█▍        | 338/2448 [40:13<4:40:26,  7.97s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 14%|█▍        | 345/2448 [40:56<2:26:54,  4.19s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 15%|█▍        | 355/2448 [41:40<2:37:00,  4.50s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 15%|█▍        | 356/2448 [42:02<5:40:35,  9.77s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 15%|█▍        | 359/2448 [42:25<4:56:55,  8.53s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 15%|█▍        | 360/2448 [42:36<5:21:04,  9.23s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 15%|█▍        | 361/2448 [42:49<5:57:27, 10.28s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 15%|█▍        | 363/2448 [43:31<8:20:25, 14.40s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 15%|█▍        | 364/2448 [43:49<8:55:23, 15.41s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 15%|█▍        | 366/2448 [44:13<7:37:03, 13.17s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 15%|█▍        | 367/2448 [44:31<8:28:52, 14.67s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 15%|█▌        | 368/2448 [44:44<8:09:25, 14.12s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 15%|█▌        | 370/2448 [44:59<6:16:22, 10.87s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 15%|█▌        | 373/2448 [45:36<6:14:47, 10.84s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 16%|█▌        | 384/2448 [46:43<3:32:58,  6.19s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 16%|█▌        | 387/2448 [47:00<3:05:59,  5.41s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 16%|█▋        | 400/2448 [48:36<4:32:14,  7.98s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 16%|█▋        | 403/2448 [49:03<4:24:05,  7.75s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 17%|█▋        | 404/2448 [49:22<6:13:08, 10.95s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 17%|█▋        | 406/2448 [49:40<5:22:29,  9.48s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 17%|█▋        | 415/2448 [50:31<3:23:05,  5.99s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 17%|█▋        | 424/2448 [51:24<2:23:42,  4.26s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 17%|█▋        | 425/2448 [51:33<3:12:54,  5.72s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 18%|█▊        | 440/2448 [53:03<2:03:47,  3.70s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 18%|█▊        | 444/2448 [53:21<2:12:53,  3.98s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 18%|█▊        | 445/2448 [53:29<2:54:27,  5.23s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 18%|█▊        | 446/2448 [53:49<5:22:25,  9.66s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 18%|█▊        | 447/2448 [54:13<7:37:13, 13.71s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 18%|█▊        | 448/2448 [54:38<9:33:40, 17.21s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 18%|█▊        | 449/2448 [54:47<8:15:10, 14.86s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 18%|█▊        | 450/2448 [55:06<8:51:28, 15.96s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 18%|█▊        | 451/2448 [55:30<10:11:03, 18.36s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 18%|█▊        | 452/2448 [56:15<14:42:53, 26.54s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 19%|█▊        | 453/2448 [57:00<17:40:03, 31.88s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 19%|█▊        | 454/2448 [57:50<20:37:59, 37.25s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 19%|█▊        | 456/2448 [58:13<12:57:50, 23.43s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 19%|█▊        | 457/2448 [58:35<12:45:59, 23.08s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 19%|█▉        | 463/2448 [58:56<2:44:24,  4.97s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 20%|█▉        | 487/2448 [1:00:48<2:27:27,  4.51s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 20%|██        | 490/2448 [1:01:21<5:02:26,  9.27s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 20%|██        | 493/2448 [1:01:54<5:17:05,  9.73s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 20%|██        | 495/2448 [1:02:21<5:51:41, 10.80s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 21%|██        | 511/2448 [1:04:07<3:07:10,  5.80s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 21%|██        | 516/2448 [1:05:20<4:43:17,  8.80s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 21%|██        | 520/2448 [1:05:42<3:08:11,  5.86s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 21%|██▏       | 522/2448 [1:06:09<4:41:41,  8.78s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 21%|██▏       | 523/2448 [1:06:21<5:10:06,  9.67s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 22%|██▏       | 528/2448 [1:07:16<4:20:56,  8.15s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 22%|██▏       | 540/2448 [1:09:13<2:30:01,  4.72s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 22%|██▏       | 541/2448 [1:10:17<11:56:46, 22.55s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 22%|██▏       | 542/2448 [1:10:36<11:23:33, 21.52s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 22%|██▏       | 543/2448 [1:10:47<9:43:06, 18.37s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 22%|██▏       | 546/2448 [1:11:38<9:20:07, 17.67s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 22%|██▏       | 547/2448 [1:12:05<10:48:13, 20.46s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 23%|██▎       | 552/2448 [1:12:45<4:15:27,  8.08s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 23%|██▎       | 555/2448 [1:13:26<5:22:39, 10.23s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 23%|██▎       | 560/2448 [1:13:48<2:27:59,  4.70s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 23%|██▎       | 564/2448 [1:14:40<4:30:27,  8.61s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 23%|██▎       | 565/2448 [1:14:48<4:28:03,  8.54s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 23%|██▎       | 572/2448 [1:16:04<4:05:55,  7.87s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 23%|██▎       | 573/2448 [1:16:19<5:13:27, 10.03s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 23%|██▎       | 574/2448 [1:16:57<9:36:38, 18.46s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 23%|██▎       | 575/2448 [1:17:09<8:31:50, 16.40s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 24%|██▎       | 578/2448 [1:17:28<4:45:01,  9.15s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 24%|██▎       | 580/2448 [1:17:42<3:57:45,  7.64s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 24%|██▍       | 583/2448 [1:18:12<4:14:19,  8.18s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 24%|██▍       | 584/2448 [1:18:26<5:05:46,  9.84s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 24%|██▍       | 587/2448 [1:18:49<4:06:14,  7.94s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 24%|██▍       | 588/2448 [1:19:09<6:03:19, 11.72s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 24%|██▍       | 589/2448 [1:19:19<5:46:28, 11.18s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 24%|██▍       | 591/2448 [1:19:37<4:56:10,  9.57s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 24%|██▍       | 592/2448 [1:19:53<5:56:48, 11.53s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 24%|██▍       | 593/2448 [1:20:21<8:26:43, 16.39s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 24%|██▍       | 595/2448 [1:20:53<8:07:16, 15.78s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 24%|██▍       | 596/2448 [1:21:18<9:36:52, 18.69s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 24%|██▍       | 597/2448 [1:21:37<9:39:17, 18.78s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 25%|██▍       | 603/2448 [1:22:42<4:56:52,  9.65s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 25%|██▍       | 604/2448 [1:23:06<7:04:19, 13.81s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 25%|██▍       | 607/2448 [1:23:37<5:07:11, 10.01s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 25%|██▍       | 611/2448 [1:24:06<3:25:13,  6.70s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 25%|██▌       | 615/2448 [1:24:43<3:31:30,  6.92s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 25%|██▌       | 616/2448 [1:24:54<4:07:51,  8.12s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 25%|██▌       | 618/2448 [1:25:08<3:40:23,  7.23s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 26%|██▌       | 629/2448 [1:26:28<4:06:30,  8.13s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 26%|██▌       | 634/2448 [1:27:52<5:13:28, 10.37s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 26%|██▌       | 635/2448 [1:28:14<6:53:24, 13.68s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 26%|██▌       | 637/2448 [1:28:26<4:47:19,  9.52s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 26%|██▌       | 641/2448 [1:29:09<3:56:55,  7.87s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 26%|██▋       | 644/2448 [1:29:29<3:12:30,  6.40s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 27%|██▋       | 654/2448 [1:30:42<5:04:52, 10.20s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 27%|██▋       | 655/2448 [1:30:52<5:06:36, 10.26s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 27%|██▋       | 659/2448 [1:31:41<5:11:12, 10.44s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 27%|██▋       | 671/2448 [1:32:59<1:55:28,  3.90s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 28%|██▊       | 674/2448 [1:33:37<3:51:43,  7.84s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 28%|██▊       | 676/2448 [1:33:48<3:13:22,  6.55s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 28%|██▊       | 677/2448 [1:33:56<3:25:22,  6.96s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 28%|██▊       | 695/2448 [1:35:36<2:07:20,  4.36s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 28%|██▊       | 697/2448 [1:36:00<3:40:17,  7.55s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 29%|██▊       | 698/2448 [1:36:19<5:18:53, 10.93s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 29%|██▊       | 703/2448 [1:36:51<2:53:34,  5.97s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 29%|██▉       | 705/2448 [1:37:06<3:06:36,  6.42s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 29%|██▉       | 706/2448 [1:37:15<3:33:37,  7.36s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 29%|██▉       | 713/2448 [1:37:55<2:09:56,  4.49s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 29%|██▉       | 714/2448 [1:38:08<3:27:07,  7.17s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 29%|██▉       | 715/2448 [1:38:31<5:41:55, 11.84s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 29%|██▉       | 722/2448 [1:39:25<3:53:13,  8.11s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 30%|██▉       | 728/2448 [1:39:52<2:02:05,  4.26s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 30%|██▉       | 731/2448 [1:40:07<2:06:49,  4.43s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 30%|██▉       | 732/2448 [1:40:25<4:03:26,  8.51s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 30%|██▉       | 733/2448 [1:40:44<5:33:35, 11.67s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 30%|██▉       | 734/2448 [1:41:08<7:16:07, 15.27s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 30%|███       | 742/2448 [1:41:47<2:23:43,  5.06s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 31%|███       | 753/2448 [1:42:47<1:58:27,  4.19s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 31%|███       | 761/2448 [1:43:43<3:04:03,  6.55s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 31%|███       | 763/2448 [1:43:54<2:45:12,  5.88s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 31%|███▏      | 770/2448 [1:44:50<4:34:48,  9.83s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 32%|███▏      | 777/2448 [1:45:40<3:58:31,  8.56s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 32%|███▏      | 778/2448 [1:46:00<5:30:07, 11.86s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 34%|███▍      | 830/2448 [1:48:28<55:05,  2.04s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 37%|███▋      | 906/2448 [1:51:29<59:08,  2.30s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 37%|███▋      | 907/2448 [1:51:36<1:39:11,  3.86s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 38%|███▊      | 935/2448 [1:53:11<1:45:44,  4.19s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 38%|███▊      | 939/2448 [1:53:35<2:05:51,  5.00s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 39%|███▊      | 946/2448 [1:54:45<2:52:40,  6.90s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 39%|███▊      | 947/2448 [1:55:06<4:39:51, 11.19s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 40%|███▉      | 973/2448 [1:56:50<2:53:48,  7.07s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 40%|███▉      | 974/2448 [1:57:15<5:02:18, 12.31s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 40%|███▉      | 975/2448 [1:57:34<5:53:35, 14.40s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 40%|███▉      | 977/2448 [1:57:44<3:48:02,  9.30s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 40%|███▉      | 978/2448 [1:58:19<6:59:43, 17.13s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 43%|████▎     | 1043/2448 [2:01:59<50:13,  2.15s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 43%|████▎     | 1049/2448 [2:02:24<1:28:34,  3.80s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 44%|████▍     | 1078/2448 [2:03:49<54:57,  2.41s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 44%|████▍     | 1080/2448 [2:04:09<2:10:42,  5.73s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 45%|████▍     | 1094/2448 [2:04:52<1:29:17,  3.96s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 45%|████▍     | 1095/2448 [2:05:35<5:56:55, 15.83s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 45%|████▌     | 1103/2448 [2:06:57<3:32:41,  9.49s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 45%|████▌     | 1110/2448 [2:07:45<1:59:05,  5.34s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 46%|████▌     | 1121/2448 [2:08:53<2:06:22,  5.71s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 46%|████▌     | 1125/2448 [2:10:32<5:48:20, 15.80s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 46%|████▌     | 1127/2448 [2:11:09<5:46:44, 15.75s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 46%|████▋     | 1134/2448 [2:11:58<3:09:30,  8.65s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 46%|████▋     | 1137/2448 [2:12:39<3:27:26,  9.49s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 47%|████▋     | 1151/2448 [2:14:03<1:22:17,  3.81s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 48%|████▊     | 1170/2448 [2:14:59<43:38,  2.05s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 52%|█████▏    | 1264/2448 [2:19:02<45:31,  2.31s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 54%|█████▍    | 1329/2448 [2:22:21<1:13:38,  3.95s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 54%|█████▍    | 1330/2448 [2:22:38<2:22:58,  7.67s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 56%|█████▋    | 1377/2448 [2:27:32<1:55:04,  6.45s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 56%|█████▋    | 1378/2448 [2:27:49<2:51:36,  9.62s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 57%|█████▋    | 1396/2448 [2:29:06<37:56,  2.16s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 57%|█████▋    | 1397/2448 [2:29:24<1:59:44,  6.84s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 57%|█████▋    | 1399/2448 [2:29:45<2:25:47,  8.34s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 59%|█████▊    | 1434/2448 [2:33:17<1:00:28,  3.58s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 59%|█████▊    | 1437/2448 [2:33:33<1:11:15,  4.23s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 59%|█████▉    | 1441/2448 [2:34:13<1:45:10,  6.27s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 59%|█████▉    | 1442/2448 [2:34:26<2:16:10,  8.12s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 59%|█████▉    | 1443/2448 [2:34:46<3:18:58, 11.88s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 61%|██████    | 1494/2448 [2:38:04<1:26:22,  5.43s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 68%|██████▊   | 1658/2448 [2:45:05<30:31,  2.32s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 72%|███████▏  | 1769/2448 [2:50:01<34:49,  3.08s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 72%|███████▏  | 1770/2448 [2:50:18<1:21:41,  7.23s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 72%|███████▏  | 1771/2448 [2:51:27<4:50:37, 25.76s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 72%|███████▏  | 1772/2448 [2:52:21<6:26:18, 34.29s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 72%|███████▏  | 1773/2448 [2:52:31<5:04:53, 27.10s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 73%|███████▎  | 1775/2448 [2:53:26<4:40:10, 24.98s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 73%|███████▎  | 1793/2448 [2:55:04<1:11:44,  6.57s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 73%|███████▎  | 1794/2448 [2:55:29<2:10:36, 11.98s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 73%|███████▎  | 1795/2448 [2:56:12<3:51:48, 21.30s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 73%|███████▎  | 1796/2448 [2:56:35<3:58:35, 21.96s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 73%|███████▎  | 1797/2448 [2:56:56<3:55:40, 21.72s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 73%|███████▎  | 1798/2448 [2:57:18<3:55:47, 21.77s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 73%|███████▎  | 1799/2448 [2:57:41<3:58:50, 22.08s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 74%|███████▎  | 1800/2448 [2:58:05<4:04:17, 22.62s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 74%|███████▎  | 1801/2448 [2:58:28<4:04:39, 22.69s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 74%|███████▎  | 1802/2448 [2:58:50<4:01:32, 22.43s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 74%|███████▎  | 1803/2448 [2:59:11<3:58:50, 22.22s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 74%|███████▎  | 1804/2448 [2:59:36<4:04:52, 22.81s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 74%|███████▍  | 1806/2448 [3:00:04<3:07:17, 17.50s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 74%|███████▍  | 1807/2448 [3:00:30<3:33:49, 20.01s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 74%|███████▍  | 1808/2448 [3:00:53<3:41:55, 20.81s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 74%|███████▍  | 1809/2448 [3:01:16<3:49:57, 21.59s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 74%|███████▍  | 1810/2448 [3:01:26<3:13:14, 18.17s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 74%|███████▍  | 1811/2448 [3:01:49<3:26:06, 19.41s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 74%|███████▍  | 1812/2448 [3:02:11<3:34:34, 20.24s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 74%|███████▍  | 1813/2448 [3:02:33<3:42:03, 20.98s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 74%|███████▍  | 1814/2448 [3:02:59<3:55:42, 22.31s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 74%|███████▍  | 1815/2448 [3:03:22<3:57:09, 22.48s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 74%|███████▍  | 1817/2448 [3:04:02<3:39:41, 20.89s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 74%|███████▍  | 1818/2448 [3:04:29<3:59:12, 22.78s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 74%|███████▍  | 1820/2448 [3:05:11<3:44:15, 21.43s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 74%|███████▍  | 1822/2448 [3:06:00<3:48:58, 21.95s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 75%|███████▍  | 1824/2448 [3:06:38<3:29:39, 20.16s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▍  | 1825/2448 [3:07:07<3:57:36, 22.88s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▍  | 1826/2448 [3:07:32<4:01:46, 23.32s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▍  | 1827/2448 [3:07:54<3:57:52, 22.98s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▍  | 1828/2448 [3:08:19<4:05:20, 23.74s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▍  | 1829/2448 [3:08:43<4:06:03, 23.85s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 75%|███████▍  | 1830/2448 [3:09:08<4:08:24, 24.12s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▍  | 1831/2448 [3:09:34<4:13:31, 24.65s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▍  | 1832/2448 [3:09:58<4:12:08, 24.56s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▍  | 1833/2448 [3:10:24<4:15:05, 24.89s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▍  | 1834/2448 [3:10:50<4:17:45, 25.19s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▍  | 1835/2448 [3:11:20<4:32:59, 26.72s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▌  | 1836/2448 [3:11:43<4:21:01, 25.59s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▌  | 1837/2448 [3:12:17<4:46:59, 28.18s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▌  | 1838/2448 [3:12:40<4:29:07, 26.47s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▌  | 1839/2448 [3:13:04<4:20:45, 25.69s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▌  | 1840/2448 [3:13:27<4:11:38, 24.83s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▌  | 1842/2448 [3:14:14<4:04:21, 24.19s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 75%|███████▌  | 1843/2448 [3:14:42<4:15:27, 25.33s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▌  | 1844/2448 [3:15:14<4:36:12, 27.44s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▌  | 1845/2448 [3:15:38<4:23:19, 26.20s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 75%|███████▌  | 1846/2448 [3:16:06<4:28:34, 26.77s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 75%|███████▌  | 1847/2448 [3:16:36<4:37:05, 27.66s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 76%|███████▋  | 1869/2448 [3:18:50<38:40,  4.01s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 77%|███████▋  | 1882/2448 [3:19:53<47:25,  5.03s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 77%|███████▋  | 1886/2448 [3:20:32<1:16:42,  8.19s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 77%|███████▋  | 1887/2448 [3:21:32<3:41:23, 23.68s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 77%|███████▋  | 1888/2448 [3:22:13<4:29:20, 28.86s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 77%|███████▋  | 1892/2448 [3:22:39<1:41:26, 10.95s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 77%|███████▋  | 1893/2448 [3:22:49<1:38:08, 10.61s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 78%|███████▊  | 1899/2448 [3:23:23<55:16,  6.04s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 78%|███████▊  | 1909/2448 [3:24:07<34:00,  3.78s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 78%|███████▊  | 1910/2448 [3:24:31<1:28:40,  9.89s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 78%|███████▊  | 1911/2448 [3:24:51<1:54:10, 12.76s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 78%|███████▊  | 1912/2448 [3:25:11<2:14:16, 15.03s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 78%|███████▊  | 1913/2448 [3:25:31<2:28:14, 16.62s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 78%|███████▊  | 1914/2448 [3:25:48<2:27:50, 16.61s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 78%|███████▊  | 1915/2448 [3:26:07<2:35:03, 17.45s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 78%|███████▊  | 1916/2448 [3:26:26<2:37:16, 17.74s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 78%|███████▊  | 1917/2448 [3:26:45<2:41:22, 18.23s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 78%|███████▊  | 1918/2448 [3:27:02<2:36:55, 17.76s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 78%|███████▊  | 1919/2448 [3:27:21<2:41:19, 18.30s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 78%|███████▊  | 1920/2448 [3:27:38<2:37:16, 17.87s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 78%|███████▊  | 1921/2448 [3:27:59<2:43:50, 18.65s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▊  | 1922/2448 [3:28:21<2:53:47, 19.82s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▊  | 1923/2448 [3:28:47<3:09:17, 21.63s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▊  | 1925/2448 [3:29:08<2:13:40, 15.34s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▊  | 1926/2448 [3:29:28<2:25:18, 16.70s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▊  | 1927/2448 [3:29:48<2:32:33, 17.57s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1928/2448 [3:30:07<2:36:36, 18.07s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1929/2448 [3:30:26<2:37:19, 18.19s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1930/2448 [3:30:57<3:11:27, 22.18s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1931/2448 [3:31:15<2:59:50, 20.87s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1932/2448 [3:31:44<3:21:39, 23.45s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1933/2448 [3:32:02<3:05:22, 21.60s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1934/2448 [3:32:25<3:08:14, 21.97s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1935/2448 [3:32:41<2:53:39, 20.31s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1936/2448 [3:32:57<2:43:41, 19.18s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1937/2448 [3:33:32<3:23:43, 23.92s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1938/2448 [3:33:49<3:03:52, 21.63s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 79%|███████▉  | 1939/2448 [3:34:01<2:40:48, 18.96s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1940/2448 [3:34:19<2:35:41, 18.39s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1941/2448 [3:34:51<3:12:18, 22.76s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1942/2448 [3:35:28<3:46:51, 26.90s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1943/2448 [3:35:47<3:25:27, 24.41s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1944/2448 [3:36:04<3:06:00, 22.14s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1945/2448 [3:36:22<2:55:32, 20.94s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 79%|███████▉  | 1946/2448 [3:36:38<2:44:16, 19.64s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|███████▉  | 1947/2448 [3:36:57<2:40:54, 19.27s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|███████▉  | 1948/2448 [3:37:29<3:13:01, 23.16s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|███████▉  | 1949/2448 [3:37:51<3:09:37, 22.80s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|███████▉  | 1950/2448 [3:38:10<3:01:16, 21.84s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|███████▉  | 1951/2448 [3:38:29<2:52:45, 20.86s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|███████▉  | 1952/2448 [3:38:54<3:03:32, 22.20s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|███████▉  | 1953/2448 [3:39:11<2:50:10, 20.63s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|███████▉  | 1954/2448 [3:39:35<2:58:21, 21.66s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|███████▉  | 1955/2448 [3:39:52<2:46:33, 20.27s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|███████▉  | 1956/2448 [3:40:17<2:55:45, 21.43s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|███████▉  | 1957/2448 [3:40:36<2:51:03, 20.90s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|███████▉  | 1958/2448 [3:40:54<2:42:22, 19.88s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|████████  | 1959/2448 [3:41:22<3:02:17, 22.37s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|████████  | 1960/2448 [3:41:39<2:48:18, 20.69s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|████████  | 1961/2448 [3:41:54<2:35:56, 19.21s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|████████  | 1962/2448 [3:42:17<2:42:52, 20.11s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|████████  | 1963/2448 [3:42:59<3:36:55, 26.84s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|████████  | 1964/2448 [3:43:17<3:14:55, 24.16s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|████████  | 1966/2448 [3:43:37<2:10:16, 16.22s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 80%|████████  | 1967/2448 [3:43:53<2:10:45, 16.31s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 81%|████████  | 1977/2448 [3:44:38<27:29,  3.50s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 82%|████████▏ | 2010/2448 [3:47:07<34:30,  4.73s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 82%|████████▏ | 2011/2448 [3:47:28<1:09:44,  9.58s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 82%|████████▏ | 2012/2448 [3:47:46<1:26:35, 11.92s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 82%|████████▏ | 2013/2448 [3:48:02<1:36:48, 13.35s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 82%|████████▏ | 2015/2448 [3:48:25<1:23:50, 11.62s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 82%|████████▏ | 2016/2448 [3:48:45<1:42:37, 14.25s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 82%|████████▏ | 2019/2448 [3:49:50<1:52:54, 15.79s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 83%|████████▎ | 2021/2448 [3:50:54<2:34:52, 21.76s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 83%|████████▎ | 2022/2448 [3:51:01<2:03:58, 17.46s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 83%|████████▎ | 2037/2448 [3:51:55<18:08,  2.65s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 86%|████████▌ | 2104/2448 [3:56:25<38:07,  6.65s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 87%|████████▋ | 2141/2448 [4:00:02<19:13,  3.76s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 88%|████████▊ | 2145/2448 [4:00:40<31:13,  6.18s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 89%|████████▉ | 2181/2448 [4:03:33<19:58,  4.49s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 90%|████████▉ | 2200/2448 [4:05:23<15:08,  3.66s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 92%|█████████▏| 2244/2448 [4:08:55<22:57,  6.75s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 92%|█████████▏| 2245/2448 [4:09:05<26:59,  7.98s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 94%|█████████▎| 2294/2448 [4:11:29<07:08,  2.79s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 94%|█████████▍| 2295/2448 [4:11:47<18:39,  7.32s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 94%|█████████▍| 2296/2448 [4:12:04<25:51, 10.21s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 94%|█████████▍| 2297/2448 [4:12:31<38:16, 15.21s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 94%|█████████▍| 2298/2448 [4:12:49<40:15, 16.10s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 94%|█████████▍| 2299/2448 [4:13:13<45:42, 18.40s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 94%|█████████▍| 2300/2448 [4:13:35<48:20, 19.60s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 94%|█████████▍| 2301/2448 [4:13:52<45:51, 18.72s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 94%|█████████▍| 2302/2448 [4:14:11<45:19, 18.63s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 94%|█████████▍| 2303/2448 [4:14:28<43:57, 18.19s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 94%|█████████▍| 2304/2448 [4:14:46<43:23, 18.08s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 94%|█████████▍| 2305/2448 [4:15:07<45:16, 18.99s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 94%|█████████▍| 2306/2448 [4:15:27<45:50, 19.37s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 94%|█████████▍| 2307/2448 [4:15:45<44:50, 19.08s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 94%|█████████▍| 2313/2448 [4:16:23<14:23,  6.40s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 95%|█████████▍| 2314/2448 [4:16:52<29:27, 13.19s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 95%|█████████▍| 2315/2448 [4:17:16<36:22, 16.41s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 95%|█████████▍| 2316/2448 [4:17:40<40:54, 18.60s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 95%|█████████▍| 2317/2448 [4:18:03<43:46, 20.05s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 95%|█████████▍| 2318/2448 [4:19:00<1:06:55, 30.89s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 95%|█████████▍| 2319/2448 [4:19:39<1:11:51, 33.42s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 95%|█████████▍| 2320/2448 [4:20:06<1:07:01, 31.42s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 95%|█████████▍| 2321/2448 [4:20:29<1:01:19, 28.97s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 95%|█████████▍| 2322/2448 [4:20:52<56:59, 27.14s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 95%|█████████▍| 2323/2448 [4:21:15<54:06, 25.98s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 95%|█████████▍| 2324/2448 [4:21:36<50:31, 24.45s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 96%|█████████▌| 2349/2448 [4:26:22<16:08,  9.78s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

 96%|█████████▋| 2362/2448 [4:28:42<12:41,  8.85s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 97%|█████████▋| 2363/2448 [4:28:54<13:56,  9.84s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 97%|█████████▋| 2373/2448 [4:30:35<09:56,  7.95s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 97%|█████████▋| 2376/2448 [4:31:14<12:33, 10.46s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1

 97%|█████████▋| 2378/2448 [4:31:39<12:34, 10.78s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 97%|█████████▋| 2379/2448 [4:31:57<14:42, 12.80s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 97%|█████████▋| 2380/2448 [4:32:16<16:28, 14.54s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 3

 97%|█████████▋| 2383/2448 [4:32:51<12:49, 11.84s/it]

Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 1
Ошибка: 'NoneType' object has no attribute 'strip'
Попытка: 2

100%|██████████| 2448/2448 [4:36:35<00:00,  6.78s/it]

,id,text,true_label,pred_label,confidence,baseline_model,raw_answer
0,0,В своем произведении Горький ставит вопрос: «Ч...,human,human,0.85,deepseek/deepseek-v4-flash,"{\n ""label"": ""human"",\n ""confidence"": 0.85\n}"
1,1,"Каждый член семьи незаменим, ведь родные для н...",human,ai,0.85,deepseek/deepseek-v4-flash,"{\n ""label"": ""ai"",\n ""confidence"": 0.85\n}"
2,2,"Каждый человек должен не забывать читать, ведь...",human,human,0.85,deepseek/deepseek-v4-flash,"{\n ""label"": ""human"",\n ""confidence"": 0.85\n}"
3,3,"Пожалуй, ни для кого не будет секретом, что А....",human,human,0.85,deepseek/deepseek-v4-flash,"{\n ""label"": ""human"",\n ""confidence"": 0.85\n}"
4,4,Доброта — это хорошее отношение к другим. В да...,human,human,0.85,deepseek/deepseek-v4-flash,"{\n ""label"": ""human"",\n ""confidence"": 0.85\n}"

In [ ]:
baseline_df[
    baseline_df["baseline_model"] ==  "deepseek/deepseek-v4-flash"
]["pred_label"].value_counts(dropna=False)

pred_label
human    2046
ai        233
None      169
Name: count, dtype: int64

In [ ]:
baseline_df["true_label"].value_counts()

true_label
human    1236
ai       1212
Name: count, dtype: int64

In [ ]:
baseline_df[[
    "baseline_model",
    "true_label",
    "pred_label",
    "confidence",
    "raw_answer"
]].head(150)

,baseline_model,true_label,pred_label,confidence,raw_answer
0,deepseek/deepseek-v4-flash,human,human,0.85,"{\n ""label"": ""human"",\n ""confidence"": 0.85\n}"
1,deepseek/deepseek-v4-flash,human,ai,0.85,"{\n ""label"": ""ai"",\n ""confidence"": 0.85\n}"
2,deepseek/deepseek-v4-flash,human,human,0.85,"{\n ""label"": ""human"",\n ""confidence"": 0.85\n}"
3,deepseek/deepseek-v4-flash,human,human,0.85,"{\n ""label"": ""human"",\n ""confidence"": 0.85\n}"
4,deepseek/deepseek-v4-flash,human,human,0.85,"{\n ""label"": ""human"",\n ""confidence"": 0.85\n}"
...,...,...,...,...,...
145,deepseek/deepseek-v4-flash,human,human,0.85,"{\n ""label"": ""human"",\n ""confidence"": 0.85\n}"
146,deepseek/deepseek-v4-flash,human,human,0.85,"{\n ""label"": ""human"",\n ""confidence"": 0.85\n}"
147,deepseek/deepseek-v4-flash,human,human,0.85,"{\n ""label"": ""human"",\n ""confidence"": 0.85\n}"
148,deepseek/deepseek-v4-flash,human,human,0.70,"{\n ""label"": ""human"",\n ""confidence"": 0.7\n}"
149,deepseek/deepseek-v4-flash,human,human,0.85,"{\n ""label"": ""human"",\n ""confidence"": 0.85\n}"

In [ ]:
# метрики  отдельно для каждой baseline-модели

metrics = []

for model in BASELINE_MODELS:

    part = baseline_df[
        baseline_df["baseline_model"] == model
    ].dropna(subset=["pred_label"])

    y_true = part["true_label"].map({
        "human": 0,
        "ai": 1
    })

    y_pred = part["pred_label"].map({
        "human": 0,
        "ai": 1
    })

    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred)
    rec = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)

    metrics.append({
        "model": model,
        "accuracy": acc,
        "precision_ai": prec,
        "recall_ai": rec,
        "f1_ai": f1,
        "n": len(part)
    })

metrics_df = pd.DataFrame(metrics)

metrics_df

,model,accuracy,precision_ai,recall_ai,f1_ai,n
0,deepseek/deepseek-v4-flash,0.463361,0.180258,0.039106,0.064269,2279

In [ ]:
# по каждой модели confusion matrix

for model in BASELINE_MODELS:
    print(model)
    part = baseline_df[
        baseline_df["baseline_model"] == model
    ].dropna(subset=["pred_label"])

    y_true = part["true_label"].map({
        "human": 0,
        "ai": 1
    })

    y_pred = part["pred_label"].map({
        "human": 0,
        "ai": 1
    })

    print("Confusion matrix:")
    print(confusion_matrix(y_true, y_pred))

    print("\nClassification report:")
    print(
        classification_report(
            y_true,
            y_pred,
            target_names=["human", "ai"]
        )
    )

deepseek/deepseek-v4-flash
Confusion matrix:
[[1014  191]
 [1032   42]]

Classification report:
              precision    recall  f1-score   support

       human       0.50      0.84      0.62      1205
          ai       0.18      0.04      0.06      1074

    accuracy                           0.46      2279
   macro avg       0.34      0.44      0.34      2279
weighted avg       0.35      0.46      0.36      2279

In [ ]:
# сохраню результаты

baseline_df.to_csv(
    "llm_baseline_results.csv",
    index=False,
    encoding="utf-8-sig"
)

metrics_df.to_csv(
    "llm_baseline_metrics.csv",
    index=False,
    encoding="utf-8-sig"
)

from google.colab import files

files.download("llm_baseline_results.csv")
files.download("llm_baseline_metrics.csv")

In [ ]:
# Попробую проверииь качество бейзлайна посмоотреа roc_auk и разные трешхолды

In [14]:
import pandas as pd
import numpy as np

from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    precision_score,
    recall_score,
    f1_score,
    accuracy_score
)

# список файлов с результатами бейзлайнов
result_files = [
    "llm_baseline_results_ Gemini 3 Flash Preview.csv",
    "llm_baseline_results_deepseek-v4-flash.csv",
    "llm_baseline_results_openaigpt-5_4-mini.csv"
]

all_metrics = []

for file_name in result_files:

    df = pd.read_csv(file_name)
    df["confidence"] = pd.to_numeric(df["confidence"], errors="coerce")
        # убираю плохие строки
    df = df.dropna(subset=["true_label", "pred_label", "confidence"]).copy()
    df["y_true"] = (df["true_label"] == "ai").astype(int)

    # делаю score для класса ai
    df["ai_score"] = df.apply(
        lambda row: row["confidence"] if row["pred_label"] == "ai" else 1 - row["confidence"],
        axis=1
    )


    # считаю auc
    roc_auc = roc_auc_score(df["y_true"], df["ai_score"])
    pr_auc = average_precision_score(df["y_true"], df["ai_score"])

    # подбираю лучший threshold
    thresholds = np.arange(0.05, 1.00, 0.05)

    best_f1 = -1
    best_threshold = None
    best_precision = None
    best_recall = None
    best_accuracy = None

    for thr in thresholds:
        y_pred = (df["ai_score"] >= thr).astype(int)

        f1 = f1_score(df["y_true"], y_pred, zero_division=0)
        precision = precision_score(df["y_true"], y_pred, zero_division=0)
        recall = recall_score(df["y_true"], y_pred, zero_division=0)
        accuracy = accuracy_score(df["y_true"], y_pred)

        if f1 > best_f1:
            best_f1 = f1
            best_threshold = thr
            best_precision = precision
            best_recall = recall
            best_accuracy = accuracy

    all_metrics.append({
        "file_name": file_name,
        "roc_auc": roc_auc,
        "pr_auc": pr_auc,
        "best_threshold": best_threshold,
        "best_f1_ai": best_f1,
        "precision_ai": best_precision,
        "recall_ai": best_recall,
        "accuracy": best_accuracy,
        "n_rows": len(df)
    })

final_metrics_df = pd.DataFrame(all_metrics).sort_values("roc_auc", ascending=False)

final_metrics_df

,file_name,roc_auc,pr_auc,best_threshold,best_f1_ai,precision_ai,recall_ai,accuracy,n_rows
1,llm_baseline_results_deepseek-v4-flash.csv,0.367650,0.418643,0.05,0.640620,0.471259,1.0,0.471259,2279
0,llm_baseline_results_ Gemini 3 Flash Preview.csv,0.326000,0.424683,0.05,0.666667,0.500000,1.0,0.500000,100
2,llm_baseline_results_openaigpt-5_4-mini.csv,0.214186,0.354625,0.05,0.662295,0.495098,1.0,0.495098,2448